services:
  connectormysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: ponty
      MYSQL_PASSWORD: ponty
      MYSQL_RANDOM_ROOT_PASSWORD: "1"

  connectorwpfpm:
    image: wordpress:6-php8.1-fpm
    volumes:
      - www_data:/var/www/html
      - ./docker-wp/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./docker-wp/opcache.ini:/usr/local/etc/php/conf.d/opcache-recommended.ini
      - ./ponty-connector:/var/www/html/wp-content/plugins/ponty-connector
    environment:
      WORDPRESS_DB_HOST: connectormysql
      WORDPRESS_DB_USER: ponty
      WORDPRESS_DB_PASSWORD: ponty
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 0
    depends_on:
      - connectormysql

  connectornginx:
    image: nginx:1.15-alpine
    volumes:
      - www_data:/var/www/html
      - ./docker-wp/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8787:80"
    depends_on:
      - connectorwpfpm

  connectorphpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: on-failure:3
    depends_on:
      - connectormysql

volumes:
  db_data:
  www_data:

networks:
  default:
    name: localdevelopment
